# Generated by Django 5.2 on 2025-05-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('total_produk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('peran', models.CharField(max_length=50)),
                ('no_whatsapp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(upload_to='produk/')),
                ('stok', models.IntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('isi_pesan', models.TextField()),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.laporan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.user')),
            ],
        ),
        migrations.AddField(
            model_name='laporan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.user'),
        ),
    ]
