# Generated by Django 5.2.7 on 2026-03-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
