# Generated by Django 5.2.7 on 2026-03-04 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_alter_produk_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='waktu',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
