# Generated by Django 5.2 on 2025-05-28 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0003_alter_produk_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
