# Generated by Django 5.2.7 on 2026-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0003_alter_pesan_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
    ]
