# Generated by Django 5.2.7 on 2025-11-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0004_alter_pesan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='merek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produk',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
