# Generated by Django 5.2.7 on 2025-11-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0005_produk_merek_produk_rating_produk_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='total_produk',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='laporan',
        ),
        migrations.AddField(
            model_name='laporan',
            name='nama_pembeli',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='total_penjualan_keseluruhan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='laporan',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='peran',
            field=models.CharField(choices=[('admin', 'Admin'), ('pengguna', 'Pengguna')], default='pengguna', max_length=10),
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_interaksi', models.CharField(choices=[('view', 'View Product Detail'), ('search', 'Search')], max_length=50)),
                ('waktu_interaksi', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.produk')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_terjual', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_penjualan_detail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Catalogue.laporan')),
            ],
        ),
    ]
