# Generated by Django 5.2.7 on 2026-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0006_remove_laporan_total_produk_remove_laporan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='durasi',
            field=models.IntegerField(default=0, help_text='Lama melihat produk dalam detik'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='tipe_interaksi',
            field=models.CharField(choices=[('view', 'View Product Detail'), ('search', 'Search'), ('chat', 'WhatsApp Chat')], max_length=50),
        ),
    ]
